Declare @PayoutCurve as [TYPE_PAYOUTCURVE_IMPORT]

insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Consumption Improvement','1','0','0.99','1','Direct')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Consumption Improvement','2','1','5','0','Direct')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','1','91','90','0.25','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','2','91','91','0.5','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','3','91','92','0.25','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','4','92','90','0.25','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','5','92','91','0.25','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','6','92','92','0.5','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','7','92','93','0.25','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','8','93','90','0.4','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','9','93','91','0.4','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','10','93','92','0.4','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','11','93','93','0.5','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','12','93','94','0.25','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','13','94','90','0.6','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','14','94','91','0.6','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','15','94','92','0.6','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','16','94','93','0.5','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','17','94','94','0.5','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','18','94','95','0.25','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','19','95','90','0.75','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','20','95','91','0.65','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','21','95','92','0.65','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','22','95','93','0.6','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','23','95','94','0.5','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','24','95','95','0.5','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','25','95','96','0.5','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','26','96','90','0.75','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','27','96','91','0.75','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','28','96','92','0.7','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','29','96','93','0.65','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','30','96','94','0.6','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','31','96','95','0.65','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','32','96','96','0.75','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','33','96','97','0.5','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','34','97','90','1','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','35','97','91','0.9','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','36','97','92','0.8','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','37','97','93','0.75','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','38','97','94','0.75','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','39','97','95','0.7','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','40','97','96','0.7','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','41','97','97','0.75','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','42','97','98','0.5','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','43','98','90','1.05','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','44','98','91','1.05','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','45','98','92','1.05','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','46','98','93','1','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','47','98','94','1','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','48','98','95','0.9','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','49','98','96','0.8','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','50','98','97','0.8','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','51','98','98','0.75','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','52','98','99','0.75','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','53','99','90','1.1','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','54','99','91','1.1','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','55','99','92','1.05','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','56','99','93','1.05','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','57','99','94','1','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','58','99','95','1','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','59','99','96','0.9','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','60','99','97','0.9','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','61','99','98','0.9','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','62','99','99','0.9','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','63','99','100','0.75','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','64','99','101','0.5','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','65','100','90','1.25','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','66','100','91','1.25','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','67','100','92','1.2','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','68','100','93','1.2','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','69','100','94','1.15','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','70','100','95','1.15','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','71','100','96','1.1','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','72','100','97','1.1','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','73','100','98','1.05','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','74','100','99','1.05','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','75','100','100','1','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','76','100','101','0.75','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','77','100','102','0.5','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','78','101','90','1.25','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','79','101','91','1.25','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','80','101','92','1.25','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','81','101','93','1.25','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','82','101','94','1.2','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','83','101','95','1.2','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','84','101','96','1.15','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','85','101','97','1.15','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','86','101','98','1.1','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','87','101','99','1.1','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','88','101','100','1.05','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','89','101','101','1','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','90','101','102','0.75','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','91','101','103','0.5','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','92','101','104','0.25','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','93','101','105','0.25','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','94','101','106','0.25','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','95','101','107','0.25','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','96','102','90','1.35','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','97','102','91','1.3','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','98','102','92','1.3','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','99','102','93','1.3','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','100','102','94','1.25','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','101','102','95','1.25','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','102','102','96','1.2','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','103','102','97','1.2','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','104','102','98','1.15','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','105','102','99','1.15','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','106','102','100','1.1','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','107','102','101','1.05','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','108','102','102','1','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','109','102','103','0.75','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','110','102','104','0.5','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','111','102','105','0.5','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','112','102','106','0.35','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','113','102','107','0.3','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','114','102','108','0.25','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','115','103','90','1.4','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','116','103','91','1.35','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','117','103','92','1.35','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','118','103','93','1.35','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','119','103','94','1.3','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','120','103','95','1.3','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','121','103','96','1.25','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','122','103','97','1.25','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','123','103','98','1.2','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','124','103','99','1.2','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','125','103','100','1.15','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','126','103','101','1.1','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','127','103','102','1.05','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','128','103','103','1','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','129','103','104','0.75','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','130','103','105','0.75','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','131','103','106','0.5','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','132','103','107','0.35','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','133','103','108','0.3','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','134','103','109','0.25','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','135','104','90','1.45','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','136','104','91','1.4','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','137','104','92','1.4','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','138','104','93','1.4','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','139','104','94','1.35','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','140','104','95','1.35','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','141','104','96','1.3','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','142','104','97','1.3','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','143','104','98','1.25','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','144','104','99','1.25','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','145','104','100','1.2','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','146','104','101','1.15','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','147','104','102','1.1','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','148','104','103','1.05','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','149','104','104','1','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','150','104','105','0.9','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','151','104','106','0.75','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','152','104','107','0.5','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','153','104','108','0.35','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','154','104','109','0.3','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','155','104','110','0.25','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','156','105','90','1.5','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','157','105','91','1.45','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','158','105','92','1.45','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','159','105','93','1.45','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','160','105','94','1.4','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','161','105','95','1.4','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','162','105','96','1.35','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','163','105','97','1.35','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','164','105','98','1.3','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','165','105','99','1.3','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','166','105','100','1.25','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','167','105','101','1.2','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','168','105','102','1.15','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','169','105','103','1.1','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','170','105','104','1.05','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','171','105','105','1','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','172','105','106','0.9','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','173','105','107','0.75','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','174','105','108','0.5','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','175','105','109','0.35','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','176','105','110','0.3','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','177','106','90','1.55','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','178','106','91','1.5','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','179','106','92','1.5','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','180','106','93','1.5','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','181','106','94','1.45','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','182','106','95','1.45','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','183','106','96','1.4','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','184','106','97','1.4','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','185','106','98','1.35','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','186','106','99','1.35','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','187','106','100','1.3','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','188','106','101','1.25','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','189','106','102','1.2','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','190','106','103','1.14','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','191','106','104','1.1','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','192','106','105','1.05','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','193','106','106','1','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','194','106','107','0.9','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','195','106','108','0.75','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','196','106','109','0.5','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','197','106','110','0.35','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','198','107','90','1.6','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','199','107','91','1.55','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','200','107','92','1.55','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','201','107','93','1.55','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','202','107','94','1.5','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','203','107','95','1.5','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','204','107','96','1.45','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','205','107','97','1.45','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','206','107','98','1.4','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','207','107','99','1.4','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','208','107','100','1.35','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','209','107','101','1.3','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','210','107','102','1.25','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','211','107','103','1.2','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','212','107','104','1.14','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','213','107','105','1.1','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','214','107','106','1.05','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','215','107','107','1','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','216','107','108','0.9','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','217','107','109','0.75','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','218','107','110','0.5','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','219','108','90','1.65','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','220','108','91','1.6','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','221','108','92','1.6','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','222','108','93','1.6','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','223','108','94','1.55','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','224','108','95','1.55','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','225','108','96','1.5','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','226','108','97','1.5','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','227','108','98','1.45','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','228','108','99','1.45','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','229','108','100','1.4','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','230','108','101','1.35','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','231','108','102','1.3','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','232','108','103','1.25','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','233','108','104','1.2','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','234','108','105','1.15','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','235','108','106','1.1','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','236','108','107','1.05','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','237','108','108','1','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','238','108','109','0.9','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','239','108','110','0.75','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','240','109','90','1.7','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','241','109','91','1.65','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','242','109','92','1.65','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','243','109','93','1.65','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','244','109','94','1.6','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','245','109','95','1.6','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','246','109','96','1.55','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','247','109','97','1.55','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','248','109','98','1.5','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','249','109','99','1.5','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','250','109','100','1.45','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','251','109','101','1.4','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','252','109','102','1.35','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','253','109','103','1.3','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','254','109','104','1.25','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','255','109','105','1.2','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','256','109','106','1.15','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','257','109','107','1.1','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','258','109','108','1.05','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','259','109','109','1','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','260','109','110','0.9','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','261','110','90','2','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','262','110','91','1.85','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','263','110','92','1.7','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','264','110','93','1.7','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','265','110','94','1.65','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','266','110','95','1.65','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','267','110','96','1.6','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','268','110','97','1.6','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','269','110','98','1.55','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','270','110','99','1.55','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','271','110','100','1.5','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','272','110','101','1.45','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','273','110','102','1.4','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','274','110','103','1.35','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','275','110','104','1.3','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','276','110','105','1.25','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','277','110','106','1.2','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','278','110','107','1.15','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','279','110','108','1.1','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','280','110','109','1.05','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Expense Management','281','110','110','1','Linear')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Forecast','1','0','50','0','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Forecast','2','50','70','0.75','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Forecast','3','70','100','1','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Java','1','0','105','1.05','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Java','2','105','110','0.95','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Java','3','110',NULL,'0.9','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('JP Flw Modifier','1','119','122','1.02','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('JP Flw Modifier','2','122',NULL,'1.05','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('JP L&G Modifier','1','101','103','1.02','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('JP L&G Modifier','2','103',NULL,'1.05','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KAM','1','0','3.49','0','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KAM','2','3.5','4.99','0.25','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KAM','3','5','6.49','0.5','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KAM','4','6.5','7.99','0.75','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KAM','5','8',NULL,'1','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KPI 1','1','0','70','0','Direct')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KPI 1','2','70','100','1','Direct')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KPI 2','1','0','85','0','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KPI 2','2','85','90','0.75','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KPI 2','3','90','95','0.9','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KPI 2','4','95','100','1','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KPI 3','1','0','85','0','Direct')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KPI 3','2','85','100','1','Direct')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KPI 4','1','0','100','1','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KPI 4','2','100',NULL,'0','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KPI 5','1','0','85','0','Direct')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KPI 5','2','85','100','1','Direct')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KPI 6','1','0','85','0','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KPI 6','2','85','90','0.85','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KPI 6','3','90','99','0.95','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KPI 6','4','99',NULL,'1','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KPI 7','1','0','85','0','Direct')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KPI 7','2','85','100','1','Direct')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KPI 7','3','100',NULL,'0','Direct')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KPI 8','1','80','100','0.5','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KPI 8','2','20','80','0.8','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KPI 8','3','0','20','1','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KPI 9','1','0','79.99','0','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KPI 9','2','80','80','0.8','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KPI 9','3','80','100','1','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KPI 10','1','0','100','1','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KR CP Modifier','1','0','90','1.07','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KR CP Modifier','2','90','95','1.05','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KR CP Modifier','3','95','99.99','1.03','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KR CP Modifier','4','100','100','1','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KR CP Modifier','5','100','105','0.97','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KR CP Modifier','6','105','110','0.95','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KR CP Modifier','7','110',NULL,'0.93','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KR Veg Modifier','1','0','10','1','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KR Veg Modifier','2','10','15','0.4','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('KR Veg Modifier','3','15','20','0.1','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Modifier Collections','1','0','80','0.9','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Modifier Collections','2','80','99','1','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Modifier Collections','3','99',NULL,'1','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Modifier Net Sales','1','0','85','0.9','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Modifier Net Sales','2','85','100','1','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Modifier Net Sales','3','100',NULL,'1.1','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('PH DSO Non PLN','1','0','30','1','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('PH DSO Non PLN','2','30','40','0.9','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('PH DSO Non PLN','3','40','50','0.7','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('PH DSO Non PLN','4','50',NULL,'0','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('PH DSO PLN','1','0','60','1','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('PH DSO PLN','2','60','70','0.9','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('PH DSO PLN','3','70','80','0.7','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('PH DSO PLN','4','80',NULL,'0','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Retailer Sell-in','1','0','85','0','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Retailer Sell-in','2','85','100','6.666666666667','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Retailer Sell-in','3','100','115','3.33','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Retailer Sell-in','4','115',NULL,'0','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Retailer Sell-in 1','1','0','85','0','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Retailer Sell-in 1','2','85','100','6.666666666667','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Retailer Sell-in 1','3','100',NULL,'0','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('SFDC KPI','1','0','85','0','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('SFDC KPI','2','85','100','6.666666666667','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard','1','0','85','0','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard','2','85','100','6.666666666667','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard','3','100','115','10','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard','4','115','125','7.5','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard','5','125','150','2.5','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard','6','150',NULL,'1','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 1','1','0','85','0','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 1','2','85','100','6.666666666667','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 1','3','100','115','10','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 1','4','115','150','2.86','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 1','5','150',NULL,'1','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 10','1','0','85','0','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 10','2','85','100','6.666666666667','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 10','3','100','120','7.5','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 10','4','120',NULL,'0','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 11','1','0','85','0','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 11','2','85','115','6.666666666667','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 11','3','115',Null,'1','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 12','1','0','85','0','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 12','2','85','100','6.666666666667','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 12','3','100','120','7.5','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 12','4','120','150','2.5','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 12','5','150',NULL,'1','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 13','1','0','85','0','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 13','2','85','100','6.666666666667','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 13','3','100','120','7.5','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 13','4','120',NULL,'1','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 14','1','0','85','0','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 14','2','85','100','6.666666666667','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 14','3','100','105','7.5','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 14','4','105','110','2.5','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 14','5','110',NULL,'1','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 15','1','0','85','0','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 15','2','85','100','6.666666666667','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 15','3','100','120','10','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 15','4','120','150','2.5','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 15','5','150',NULL,'0','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 16','1','0','85','0','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 16','2','85','100','6.666666666667','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 16','3','100','110','10','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 16','4','110','120','7.5','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 16','5','120','150','2.5','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 16','6','150',NULL,'1','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 17','1','0','80','0','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 17','2','80','100','5','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 17','3','100','120','7.5','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 17','4','120',NULL,'0','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 2','1','0','85','0','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 2','2','85','100','6.666666666667','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 2','3','100','120','10','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 2','4','120','150','5','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 2','5','150',NULL,'0','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 3','1','0','90','0','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 3','2','90','100','10','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 3','3','100','110','10','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 3','4','110','130','3.33','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 3','5','130',NULL,'2','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 4','1','0','90','0','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 4','2','90','100','10','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 4','3','100','110','10','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 4','4','110','130','3.33','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 4','5','130',NULL,'0','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 5','1','0','85','0','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 5','2','85','100','6.666666666667','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 5','3','100','115','10','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 5','4','115','125','7.5','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 5','5','125','150','2.5','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 5','6','150',NULL,'0','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 6','1','0','85','0','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 6','2','85','100','6.666666666667','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 6','3','100','115','7.5','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 6','4','115','125','5','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 6','5','125','150','1','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 6','6','150',NULL,'0','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 7','1','0','85','0','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 7','2','85','100','6.666666666667','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 7','3','100','120','10','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 7','4','120','130','5','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 7','5','130','150','2.5','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 7','6','150',NULL,'1','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 8','1','0','85','0','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 8','2','85','100','6.666666666667','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 8','3','100','120','7.5','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 8','4','120','140','2.5','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 8','5','140',NULL,'0','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 9','1','0','85','0','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 9','2','85','100','6.666666666667','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 9','3','100','120','7.5','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 9','4','120','150','2.5','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Standard 9','5','150',NULL,'0','Multiplier')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Sumatra','1','0','130','1.05','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Sumatra','2','130','135','0.95','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('Sumatra','3','135',NULL,'0.9','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('TW CP Modifier','1','-20','-10','1.1','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('TW CP Modifier','2','-9.99','-5','1.05','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('TW CP Modifier','3','-4.99','5','1','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('TW CP Modifier','4','5','10','0.95','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('TW CP Modifier','5','10',NULL,'0.9','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('TW CP Modifier 1','1','-10','-5','1.1','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('TW CP Modifier 1','2','-4.99','-2','1.05','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('TW CP Modifier 1','3','-1.99','2','1','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('TW CP Modifier 1','4','2','5','0.95','Flat')
insert into @PayoutCurve(PayoutCurve,SlabId,Min,Max,Multiplier,MultiplierType)values('TW CP Modifier 1','5','5',NULL,'0.9','Flat')



update @PayoutCurve set PayoutCurve = LTRIM(RTRIM(PayoutCurve))
exec Proc_ImportPayoutCurve  @PayoutCurve

