declare @tempRole as [TYPE_ROLE_IMPORT]

insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Australia','CP','Area Sales Manager','20')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Australia','CP','Commercial Unit Head','20')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Australia','CP','Territory Sales Manager','20')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Australia','L&G Controls','Area Sales Manager (T&L)','20')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Australia','L&G Controls','Territory Sales Manager (PPM)','20')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Australia','L&G Controls','Territory Sales Manager (T&L)','20')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Australia','SEEDS','Territory Sales Manager (SC)','20')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Australia','Veg Seeds','Territory Sales Manager','20')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Bangladesh','CP','Regional Sales Manager','40')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Bangladesh','CP','Sales Unit Lead','50')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Bangladesh','CP','Zonal Sales Manager','30')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('China','CP','ASM ','46.1538')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('China','CP','BR 1 ','46.1538')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('China','CP','BR 2 ','46.1538')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('China','CP','CU Head','30.77')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('China','CP','KAM, ND','46.1538')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('China','CP','ND Mgr','46.1538')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('China','CP','Promoter 1','46.1538')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('China','CP','Promoter 2 ','46.1538')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('China','CP (SC)','BR','46.1538')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('China','CP (SC)','KAM','46.1538')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('China','CP (SC)','NSM','46.1538')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('China','CP (SC)','Promoter','46.1538')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('China','L&G Controls','Business Manager','46.1538')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('China','L&G Controls','Business Representative','46.1538')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('China','L&G Flowers','Business Representative','46.1538')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('China','Veg Seeds',' ASM (SE)','46.1538')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('China','Veg Seeds',' BR (SE)','46.1538')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('China','Veg Seeds',' NSM (SE)','46.1538')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('China','Veg Seeds',' Promoter (SE) 1','46.1538')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('China','Veg Seeds',' Promoter (SE) 2','46.1538')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Indonesia','CP','Account Executive','30')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Indonesia','CP','Agronomist','30')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Indonesia','CP','CP Commercial Area Head','30')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Indonesia','CP','CP Regional Sales Manager ','30')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Indonesia','CP','CP Regional Sales Manager Java','30')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Indonesia','CP','CP Regional Sales Manager Sumatra','30')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Indonesia','CP','Demand Creation Manager','30')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Indonesia','CP','Jr Account Executive','30')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Indonesia','CP','Jr Agronomist ','30')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Indonesia','CP','Plantation Manager','30')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Indonesia','L&G Controls','Sales & Technical Executive','30')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Indonesia','SEEDS','SE Commercial Area Head','30')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Indonesia','SEEDS','SE Jr Sales Executive','30')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Indonesia','SEEDS','SE Regional Sales Manager ','30')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Indonesia','SEEDS','SE Regional Sales Manager Java','30')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Indonesia','SEEDS','SE Regional Sales Manager Sumatra','30')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Indonesia','SEEDS','SE Sales Executive','30')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Japan','CP','Branch Manager/ Area Marketing Manager','22.22')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Japan','CP','Group Leader','22.22')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Japan','CP','Home Center Business Manager','22.22')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Japan','CP','Home Center Sales','20')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Japan','CP','Sales Assistant','20')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Japan','CP','Sr. Area Sales / Area Sales','20')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Japan','CP','Technical Sales','20')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Japan','L&G Controls','Sales Manager 1  (Turf West)','22.22')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Japan','L&G Controls','Sales Manager 2 (Turf East)','22.22')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Japan','L&G Controls','Sales Representative (LM)','20')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Japan','L&G Controls','Sales Representative (PPM)','20')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Japan','L&G Controls','Sales Representative (Turf East)','20')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Japan','L&G Controls','Sales Representative (Turf West)','20')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Japan','L&G Flowers','Sales Representative','20')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Japan','Veg Seeds','Area Sales Manager','20')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Japan','Veg Seeds','Sales Manager','22.22')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Japan','Veg Seeds','Veg BU Head','22.22')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('South Korea','CP','Area Sales Manager','20')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('South Korea','CP','Provincial Sales Manager','20')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('South Korea','CP','Technical Sales Specialist','20')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('South Korea','CP','Territory Sales Manager','20')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('South Korea','L&G Controls','Business Team Leader GC','20')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('South Korea','L&G Controls','Business Team Leader O&G','20')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('South Korea','L&G Controls','Technical Sales Manager','20')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('South Korea','Veg Seeds','Key Account Manager (Protected Crop Specialist)','20')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('South Korea','Veg Seeds','Territory Sales Manager','20')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('South Korea','Veg Seeds','Veg BU Head','23')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Malaysia','CP','Area Sales Manager','30')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Malaysia','CP','Key Account Manager','30')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Malaysia','CP','Regional Sales Manager','30')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Malaysia','CP','Techno Commercial Lead','30')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Malaysia','Veg Seeds','Veg Sales Representative','30')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Myanmar','Veg Seeds','Veg Sales Lead','15')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Myanmar','Veg Seeds','Veg Sales Representative','30')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('New Zealand','CP','Territory Sales Manager (NZ)','20')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Pakistan','CP','Regional Sales Manager','40')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Pakistan','CP','Sales Unit Lead','50')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Pakistan','CP','Zonal Sales Manager','30')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Philippines','CP','Area Lead - CP','35')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Philippines','CP','Business Unit Head - CP','35')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Philippines','CP','Plantation & Seedcare Sales Manager - PLN','35')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Philippines','CP','Plantation & Seedcare Sales Manager - Non PLN','35')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Philippines','CP','Plantation Lead - PLN','35')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Philippines','CP','Plantation Lead - Non PLN','35')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Philippines','CP','Regional Sales Manager - CP','35')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Philippines','L&G Controls','L&G Account Manager','35')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Philippines','SEEDS','Area Lead - SE','35')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Philippines','SEEDS','Business Unit Head - SE','35')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Philippines','SEEDS','Regional Sales Manager - SE','35')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Philippines','Veg Seeds','Veg Sales Lead','20')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Philippines','Veg Seeds','Veg Sales Representative','35')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Taiwan','CP','National Distributor Sales Lead','25')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Taiwan','CP','Sales Executive','25')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Taiwan','CP','Sales Manager (Mega Agent)','25')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Taiwan','CP','Sales Promoter ','25')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Thailand','CP','Area Sales Manager','30')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Thailand','CP','Key Account Mngr. (AI)','30')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Thailand','CP','Key Account Mngr. (SC)','30')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Thailand','CP','Regional Sales Manager','30')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Thailand','CP','Sales Executive','30')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Thailand','CP','Sales Promoter 3P','30')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Thailand','CP & SEEDS','Area Sales Manager','30')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Thailand','CP & SEEDS','Regional Sales Manager','30')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Thailand','CP & SEEDS','Sales Executive','30')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Thailand','Veg Seeds','Veg BU Manager','20')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Thailand','Veg Seeds','Veg Sales Lead','30')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Thailand','Veg Seeds','Veg Sales Representative','30')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Vietnam','CP','Area Sales Manager','35')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Vietnam','CP','Campaign Execution Lead','25')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Vietnam','CP','Regional Sales  Manager','35')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Vietnam','CP','Sales Executive –   Demand Creation','35')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Vietnam','CP','Sales Executive - Channel','35')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Vietnam','CP','Sales Manager','35')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Vietnam','Veg Seeds','Veg Sales Lead','35')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Vietnam','Veg Seeds','Veg Sales Representative','35')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Pakistan','CP & SEEDS','Head of Sales','20')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Singapore','L&G Flowers','Key Account Manager, Flowers','20')
insert into @tempRole(Country,BusinessUnit,Role,RoleTargetIncentive)values('Australia','L&G Flowers','Wholesale Flowers KAM','20')


update @tempRole set Country = LTRIM(RTRIM(Country))
update @tempRole set BusinessUnit = LTRIM(RTRIM(BusinessUnit))
update @tempRole set [Role] = LTRIM(RTRIM([Role]))
exec Proc_ImportRole @tempRole